[2025-04-24T18:43:09.214+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-24T18:43:09.238+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_kafka_pipeline.run_spark_test scheduled__2025-04-24T18:30:00+00:00 [queued]>
[2025-04-24T18:43:09.243+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_kafka_pipeline.run_spark_test scheduled__2025-04-24T18:30:00+00:00 [queued]>
[2025-04-24T18:43:09.243+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-24T18:43:09.256+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_spark_test> on 2025-04-24 18:30:00+00:00
[2025-04-24T18:43:09.261+0000] {standard_task_runner.py:63} INFO - Started process 123 to run task
[2025-04-24T18:43:09.263+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'stock_kafka_pipeline', 'run_spark_test', 'scheduled__2025-04-24T18:30:00+00:00', '--job-id', '286', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp96dqykdy']
[2025-04-24T18:43:09.265+0000] {standard_task_runner.py:91} INFO - Job 286: Subtask run_spark_test
[2025-04-24T18:43:09.294+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_kafka_pipeline.run_spark_test scheduled__2025-04-24T18:30:00+00:00 [running]> on host 6555ac884751
[2025-04-24T18:43:09.354+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='stock_kafka_pipeline' AIRFLOW_CTX_TASK_ID='run_spark_test' AIRFLOW_CTX_EXECUTION_DATE='2025-04-24T18:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-24T18:30:00+00:00'
[2025-04-24T18:43:09.354+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-24T18:43:09.365+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-24T18:43:09.366+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/spark-apps/test.py']
[2025-04-24T18:43:09.377+0000] {subprocess.py:86} INFO - Output:
[2025-04-24T18:43:09.444+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-04-24T18:43:09.444+0000] {subprocess.py:93} INFO -   File "/opt/spark-apps/test.py", line 1, in <module>
[2025-04-24T18:43:09.444+0000] {subprocess.py:93} INFO -     import findspark
[2025-04-24T18:43:09.444+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'findspark'
[2025-04-24T18:43:09.448+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-24T18:43:09.448+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-24T18:43:09.454+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-24T18:43:09.457+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_kafka_pipeline, task_id=run_spark_test, run_id=scheduled__2025-04-24T18:30:00+00:00, execution_date=20250424T183000, start_date=20250424T184309, end_date=20250424T184309
[2025-04-24T18:43:09.468+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 286 for task run_spark_test (Bash command failed. The command returned a non-zero exit code 1.; 123)
[2025-04-24T18:43:09.475+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-24T18:43:09.486+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-24T18:43:09.487+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
