[2025-04-22T18:27:22.890+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-22T18:27:22.915+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_kafka_pipeline.Kafka_Producer manual__2025-04-22T18:27:18.124394+00:00 [queued]>
[2025-04-22T18:27:22.921+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_kafka_pipeline.Kafka_Producer manual__2025-04-22T18:27:18.124394+00:00 [queued]>
[2025-04-22T18:27:22.921+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-22T18:27:22.933+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): Kafka_Producer> on 2025-04-22 18:27:18.124394+00:00
[2025-04-22T18:27:22.938+0000] {standard_task_runner.py:63} INFO - Started process 228 to run task
[2025-04-22T18:27:22.941+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'stock_kafka_pipeline', 'Kafka_Producer', 'manual__2025-04-22T18:27:18.124394+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/stock_kafka_pipeline.py', '--cfg-path', '/tmp/tmppm2qbrqk']
[2025-04-22T18:27:22.942+0000] {standard_task_runner.py:91} INFO - Job 81: Subtask Kafka_Producer
[2025-04-22T18:27:22.970+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_kafka_pipeline.Kafka_Producer manual__2025-04-22T18:27:18.124394+00:00 [running]> on host 6df7355a8d19
[2025-04-22T18:27:23.051+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='stock_kafka_pipeline' AIRFLOW_CTX_TASK_ID='Kafka_Producer' AIRFLOW_CTX_EXECUTION_DATE='2025-04-22T18:27:18.124394+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-22T18:27:18.124394+00:00'
[2025-04-22T18:27:23.052+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-22T18:27:23.070+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-22T18:27:23.071+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/airflow/Scripts/alpha_vantage_producer.py']
[2025-04-22T18:27:23.082+0000] {subprocess.py:86} INFO - Output:
[2025-04-22T18:27:23.903+0000] {subprocess.py:93} INFO - INFO:kafka.conn:<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.27.0.7', 9092)]>: connecting to kafka:9092 [('172.27.0.7', 9092) IPv4]
[2025-04-22T18:27:23.906+0000] {subprocess.py:93} INFO - INFO:kafka.conn:<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.27.0.7', 9092)]>: Broker version identified as 2.6
[2025-04-22T18:27:23.906+0000] {subprocess.py:93} INFO - INFO:kafka.conn:<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.27.0.7', 9092)]>: Connection complete.
[2025-04-22T18:27:23.907+0000] {subprocess.py:93} INFO - INFO:__main__:Alpha Vantage producer started for symbols: ['IBM', 'AAPL', 'MSFT', 'TSLA']
[2025-04-22T18:27:24.440+0000] {subprocess.py:93} INFO - INFO:kafka.conn:<BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.27.0.7', 9092)]>: connecting to kafka:9092 [('172.27.0.7', 9092) IPv4]
[2025-04-22T18:27:24.441+0000] {subprocess.py:93} INFO - INFO:kafka.conn:<BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.27.0.7', 9092)]>: Connection complete.
[2025-04-22T18:27:24.441+0000] {subprocess.py:93} INFO - INFO:kafka.conn:<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.27.0.7', 9092)]>: Closing connection.
[2025-04-22T18:27:24.445+0000] {subprocess.py:93} INFO - INFO:__main__:Published data for IBM to topic 'stock-prices'
[2025-04-22T18:27:36.950+0000] {subprocess.py:93} INFO - INFO:__main__:Published data for AAPL to topic 'stock-prices'
[2025-04-22T18:27:48.177+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-04-22T18:27:48.178+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-22T18:27:48.179+0000] {process_utils.py:132} INFO - Sending 15 to group 228. PIDs of all processes in the group: [229, 228]
[2025-04-22T18:27:48.180+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 228
[2025-04-22T18:27:48.180+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-04-22T18:27:48.180+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-04-22T18:27:48.181+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-22T18:27:48.232+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=228, status='terminated', exitcode=0, started='18:27:22') (228) terminated with exit code 0
[2025-04-22T18:27:48.233+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=229, status='terminated', started='18:27:22') (229) terminated with exit code None
