[2025-04-25T11:18:55.329+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-25T11:18:55.351+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_kafka_pipeline.run_spark_test scheduled__2025-04-25T11:00:00+00:00 [queued]>
[2025-04-25T11:18:55.357+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_kafka_pipeline.run_spark_test scheduled__2025-04-25T11:00:00+00:00 [queued]>
[2025-04-25T11:18:55.357+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-25T11:18:55.369+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_spark_test> on 2025-04-25 11:00:00+00:00
[2025-04-25T11:18:55.375+0000] {standard_task_runner.py:63} INFO - Started process 327 to run task
[2025-04-25T11:18:55.377+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'stock_kafka_pipeline', 'run_spark_test', 'scheduled__2025-04-25T11:00:00+00:00', '--job-id', '380', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp3h218vxk']
[2025-04-25T11:18:55.379+0000] {standard_task_runner.py:91} INFO - Job 380: Subtask run_spark_test
[2025-04-25T11:18:55.411+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_kafka_pipeline.run_spark_test scheduled__2025-04-25T11:00:00+00:00 [running]> on host 9489df9b8294
[2025-04-25T11:18:55.475+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='stock_kafka_pipeline' AIRFLOW_CTX_TASK_ID='run_spark_test' AIRFLOW_CTX_EXECUTION_DATE='2025-04-25T11:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-25T11:00:00+00:00'
[2025-04-25T11:18:55.476+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-25T11:18:55.487+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-25T11:18:55.488+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit  /opt/airflow/Scripts/test.py']
[2025-04-25T11:18:55.500+0000] {subprocess.py:86} INFO - Output:
[2025-04-25T11:18:55.510+0000] {subprocess.py:93} INFO - /home/airflow/.local/bin/find-spark-home: line 40: /usr/local/bin/python3.10: No such file or directory
[2025-04-25T11:18:55.510+0000] {subprocess.py:93} INFO - /home/airflow/.local/bin/spark-submit: line 27: /bin/spark-class: No such file or directory
[2025-04-25T11:18:55.510+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-04-25T11:18:55.511+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-25T11:18:55.517+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-04-25T11:18:55.521+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_kafka_pipeline, task_id=run_spark_test, run_id=scheduled__2025-04-25T11:00:00+00:00, execution_date=20250425T110000, start_date=20250425T111855, end_date=20250425T111855
[2025-04-25T11:18:55.533+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 380 for task run_spark_test (Bash command failed. The command returned a non-zero exit code 127.; 327)
[2025-04-25T11:18:55.549+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-25T11:18:55.561+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-25T11:18:55.562+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
