[2025-04-22T13:17:14.132+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-22T13:17:14.157+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_kafka_pipeline.Kafka_Consumer manual__2025-04-22T13:13:53.759258+00:00 [queued]>
[2025-04-22T13:17:14.164+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_kafka_pipeline.Kafka_Consumer manual__2025-04-22T13:13:53.759258+00:00 [queued]>
[2025-04-22T13:17:14.164+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 4
[2025-04-22T13:17:14.175+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): Kafka_Consumer> on 2025-04-22 13:13:53.759258+00:00
[2025-04-22T13:17:14.181+0000] {standard_task_runner.py:63} INFO - Started process 139 to run task
[2025-04-22T13:17:14.183+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'stock_kafka_pipeline', 'Kafka_Consumer', 'manual__2025-04-22T13:13:53.759258+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/stock_kafka_pipeline.py', '--cfg-path', '/tmp/tmpqe0nt4kp']
[2025-04-22T13:17:14.184+0000] {standard_task_runner.py:91} INFO - Job 28: Subtask Kafka_Consumer
[2025-04-22T13:17:14.212+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_kafka_pipeline.Kafka_Consumer manual__2025-04-22T13:13:53.759258+00:00 [running]> on host c25f8f7dc196
[2025-04-22T13:17:14.265+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='stock_kafka_pipeline' AIRFLOW_CTX_TASK_ID='Kafka_Consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-04-22T13:13:53.759258+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-22T13:13:53.759258+00:00'
[2025-04-22T13:17:14.266+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-22T13:17:14.280+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-22T13:17:14.281+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/airflow/Scripts/load_to_bronze.py']
[2025-04-22T13:17:14.291+0000] {subprocess.py:86} INFO - Output:
[2025-04-22T13:17:49.466+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-04-22T13:17:49.467+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-22T13:17:49.468+0000] {process_utils.py:132} INFO - Sending 15 to group 139. PIDs of all processes in the group: [140, 139]
[2025-04-22T13:17:49.468+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 139
[2025-04-22T13:17:49.468+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-04-22T13:17:49.469+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-04-22T13:17:49.469+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-22T13:17:49.495+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=139, status='terminated', exitcode=0, started='13:17:13') (139) terminated with exit code 0
[2025-04-22T13:17:49.495+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=140, status='terminated', started='13:17:13') (140) terminated with exit code None
