[2025-04-22T13:11:11.179+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-22T13:11:11.214+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_kafka_pipeline.Kafka_Producer scheduled__2025-04-22T13:00:00+00:00 [queued]>
[2025-04-22T13:11:11.223+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_kafka_pipeline.Kafka_Producer scheduled__2025-04-22T13:00:00+00:00 [queued]>
[2025-04-22T13:11:11.223+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-04-22T13:11:11.241+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): Kafka_Producer> on 2025-04-22 13:00:00+00:00
[2025-04-22T13:11:11.247+0000] {standard_task_runner.py:63} INFO - Started process 133 to run task
[2025-04-22T13:11:11.249+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'stock_kafka_pipeline', 'Kafka_Producer', 'scheduled__2025-04-22T13:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/stock_kafka_pipeline.py', '--cfg-path', '/tmp/tmp12k3b12a']
[2025-04-22T13:11:11.250+0000] {standard_task_runner.py:91} INFO - Job 23: Subtask Kafka_Producer
[2025-04-22T13:11:11.280+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_kafka_pipeline.Kafka_Producer scheduled__2025-04-22T13:00:00+00:00 [running]> on host 9b76f220bc2e
[2025-04-22T13:11:11.336+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='stock_kafka_pipeline' AIRFLOW_CTX_TASK_ID='Kafka_Producer' AIRFLOW_CTX_EXECUTION_DATE='2025-04-22T13:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-22T13:00:00+00:00'
[2025-04-22T13:11:11.337+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-22T13:11:11.351+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-22T13:11:11.352+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/airflow/Scripts/alpha_vantage_producer.py']
[2025-04-22T13:11:11.363+0000] {subprocess.py:86} INFO - Output:
[2025-04-22T13:11:14.177+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-04-22T13:11:14.177+0000] {subprocess.py:93} INFO -   File "/opt/airflow/Scripts/alpha_vantage_producer.py", line 14, in <module>
[2025-04-22T13:11:14.177+0000] {subprocess.py:93} INFO -     producer = KafkaProducer(
[2025-04-22T13:11:14.177+0000] {subprocess.py:93} INFO -                ^^^^^^^^^^^^^^
[2025-04-22T13:11:14.178+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py", line 408, in __init__
[2025-04-22T13:11:14.178+0000] {subprocess.py:93} INFO -     client = self.config['kafka_client'](
[2025-04-22T13:11:14.178+0000] {subprocess.py:93} INFO -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-22T13:11:14.178+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py", line 262, in __init__
[2025-04-22T13:11:14.178+0000] {subprocess.py:93} INFO -     self.config['api_version'] = self.check_version()
[2025-04-22T13:11:14.178+0000] {subprocess.py:93} INFO -                                  ^^^^^^^^^^^^^^^^^^^^
[2025-04-22T13:11:14.178+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py", line 1073, in check_version
[2025-04-22T13:11:14.178+0000] {subprocess.py:93} INFO -     raise Errors.NoBrokersAvailable()
[2025-04-22T13:11:14.179+0000] {subprocess.py:93} INFO - kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-04-22T13:11:14.259+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-22T13:11:14.260+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-22T13:11:14.266+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-22T13:11:14.269+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=stock_kafka_pipeline, task_id=Kafka_Producer, run_id=scheduled__2025-04-22T13:00:00+00:00, execution_date=20250422T130000, start_date=20250422T131111, end_date=20250422T131114
[2025-04-22T13:11:14.279+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 23 for task Kafka_Producer (Bash command failed. The command returned a non-zero exit code 1.; 133)
[2025-04-22T13:11:14.309+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-22T13:11:14.339+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-22T13:11:14.346+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
