[2025-04-25T05:38:02.867+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-25T05:38:02.887+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_kafka_pipeline.run_spark_test scheduled__2025-04-25T05:20:00+00:00 [queued]>
[2025-04-25T05:38:02.892+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_kafka_pipeline.run_spark_test scheduled__2025-04-25T05:20:00+00:00 [queued]>
[2025-04-25T05:38:02.893+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-25T05:38:02.904+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_spark_test> on 2025-04-25 05:20:00+00:00
[2025-04-25T05:38:02.910+0000] {standard_task_runner.py:63} INFO - Started process 105 to run task
[2025-04-25T05:38:02.912+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'stock_kafka_pipeline', 'run_spark_test', 'scheduled__2025-04-25T05:20:00+00:00', '--job-id', '321', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp6sha2puz']
[2025-04-25T05:38:02.913+0000] {standard_task_runner.py:91} INFO - Job 321: Subtask run_spark_test
[2025-04-25T05:38:02.942+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_kafka_pipeline.run_spark_test scheduled__2025-04-25T05:20:00+00:00 [running]> on host b8ca48d3e41a
[2025-04-25T05:38:02.991+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='stock_kafka_pipeline' AIRFLOW_CTX_TASK_ID='run_spark_test' AIRFLOW_CTX_EXECUTION_DATE='2025-04-25T05:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-25T05:20:00+00:00'
[2025-04-25T05:38:02.992+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-25T05:38:03.001+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-25T05:38:03.002+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit /opt/airflow/Scripts/test.py']
[2025-04-25T05:38:03.013+0000] {subprocess.py:86} INFO - Output:
[2025-04-25T05:38:06.277+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-04-25T05:38:06.277+0000] {subprocess.py:93} INFO -   File "/opt/airflow/Scripts/test.py", line 1, in <module>
[2025-04-25T05:38:06.277+0000] {subprocess.py:93} INFO -     from pyspark.sql import SparkContext ,SparkConf
[2025-04-25T05:38:06.277+0000] {subprocess.py:93} INFO - ImportError: cannot import name 'SparkContext' from 'pyspark.sql' (/home/airflow/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/__init__.py). Did you mean: 'SQLContext'?
[2025-04-25T05:38:06.325+0000] {subprocess.py:93} INFO - 25/04/25 05:38:06 INFO ShutdownHookManager: Shutdown hook called
[2025-04-25T05:38:06.332+0000] {subprocess.py:93} INFO - 25/04/25 05:38:06 INFO ShutdownHookManager: Deleting directory /tmp/spark-27495e3e-9e90-4035-b345-393e6fedafea
[2025-04-25T05:38:06.364+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-25T05:38:06.365+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-25T05:38:06.370+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-25T05:38:06.372+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_kafka_pipeline, task_id=run_spark_test, run_id=scheduled__2025-04-25T05:20:00+00:00, execution_date=20250425T052000, start_date=20250425T053802, end_date=20250425T053806
[2025-04-25T05:38:06.384+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 321 for task run_spark_test (Bash command failed. The command returned a non-zero exit code 1.; 105)
[2025-04-25T05:38:06.412+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-25T05:38:06.433+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-25T05:38:06.433+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
