[2025-04-25T11:22:31.315+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: stock_kafka_pipeline.run_spark_test scheduled__2025-04-25T11:10:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
