[2025-04-25T11:27:55.159+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-25T11:27:55.185+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_kafka_pipeline.run_spark_test scheduled__2025-04-25T11:10:00+00:00 [queued]>
[2025-04-25T11:27:55.190+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_kafka_pipeline.run_spark_test scheduled__2025-04-25T11:10:00+00:00 [queued]>
[2025-04-25T11:27:55.191+0000] {taskinstance.py:2306} INFO - Starting attempt 6 of 7
[2025-04-25T11:27:55.202+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_spark_test> on 2025-04-25 11:10:00+00:00
[2025-04-25T11:27:55.207+0000] {standard_task_runner.py:63} INFO - Started process 53 to run task
[2025-04-25T11:27:55.209+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'stock_kafka_pipeline', 'run_spark_test', 'scheduled__2025-04-25T11:10:00+00:00', '--job-id', '391', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpqrccy5gr']
[2025-04-25T11:27:55.211+0000] {standard_task_runner.py:91} INFO - Job 391: Subtask run_spark_test
[2025-04-25T11:27:55.242+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_kafka_pipeline.run_spark_test scheduled__2025-04-25T11:10:00+00:00 [running]> on host 349fc04af263
[2025-04-25T11:27:55.306+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='stock_kafka_pipeline' AIRFLOW_CTX_TASK_ID='run_spark_test' AIRFLOW_CTX_EXECUTION_DATE='2025-04-25T11:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-25T11:10:00+00:00'
[2025-04-25T11:27:55.307+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-25T11:27:55.334+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-25T11:27:55.334+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'pyspark --master spark://172.21.0.8:7077 /opt/spark/source/test.py']
[2025-04-25T11:27:55.344+0000] {subprocess.py:86} INFO - Output:
[2025-04-25T11:27:55.906+0000] {subprocess.py:93} INFO - Running python applications through 'pyspark' is not supported as of Spark 2.0.
[2025-04-25T11:27:55.906+0000] {subprocess.py:93} INFO - Use ./bin/spark-submit <python file>
[2025-04-25T11:27:55.922+0000] {subprocess.py:93} INFO - /home/airflow/.local/lib/python3.12/site-packages/pyspark/bin/spark-class: line 97: CMD: bad array subscript
[2025-04-25T11:27:55.925+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-25T11:27:55.926+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-25T11:27:55.931+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-25T11:27:55.935+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_kafka_pipeline, task_id=run_spark_test, run_id=scheduled__2025-04-25T11:10:00+00:00, execution_date=20250425T111000, start_date=20250425T112755, end_date=20250425T112755
[2025-04-25T11:27:55.946+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 391 for task run_spark_test (Bash command failed. The command returned a non-zero exit code 1.; 53)
[2025-04-25T11:27:55.983+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-25T11:27:55.997+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-25T11:27:55.997+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
