[2025-04-22T12:58:00.790+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-22T12:58:00.816+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_kafka_pipeline.Kafka_Producer scheduled__2025-04-22T12:40:00+00:00 [queued]>
[2025-04-22T12:58:00.823+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_kafka_pipeline.Kafka_Producer scheduled__2025-04-22T12:40:00+00:00 [queued]>
[2025-04-22T12:58:00.824+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 4
[2025-04-22T12:58:00.837+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): Kafka_Producer> on 2025-04-22 12:40:00+00:00
[2025-04-22T12:58:00.843+0000] {standard_task_runner.py:63} INFO - Started process 163 to run task
[2025-04-22T12:58:00.845+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'stock_kafka_pipeline', 'Kafka_Producer', 'scheduled__2025-04-22T12:40:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/stock_kafka_pipeline.py', '--cfg-path', '/tmp/tmpepzin7yu']
[2025-04-22T12:58:00.847+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask Kafka_Producer
[2025-04-22T12:58:00.878+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_kafka_pipeline.Kafka_Producer scheduled__2025-04-22T12:40:00+00:00 [running]> on host 1705554292e6
[2025-04-22T12:58:00.939+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='stock_kafka_pipeline' AIRFLOW_CTX_TASK_ID='Kafka_Producer' AIRFLOW_CTX_EXECUTION_DATE='2025-04-22T12:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-22T12:40:00+00:00'
[2025-04-22T12:58:00.940+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-22T12:58:00.954+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-22T12:58:00.955+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/airflow/Scripts/alpha_vantage_producer.py']
[2025-04-22T12:58:00.965+0000] {subprocess.py:86} INFO - Output:
[2025-04-22T12:58:01.549+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-04-22T12:58:01.549+0000] {subprocess.py:93} INFO -   File "/opt/airflow/Scripts/alpha_vantage_producer.py", line 5, in <module>
[2025-04-22T12:58:01.550+0000] {subprocess.py:93} INFO -     from kafka import KafkaProducer
[2025-04-22T12:58:01.550+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'kafka'
[2025-04-22T12:58:01.583+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-22T12:58:01.584+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-22T12:58:01.592+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-22T12:58:01.595+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_kafka_pipeline, task_id=Kafka_Producer, run_id=scheduled__2025-04-22T12:40:00+00:00, execution_date=20250422T124000, start_date=20250422T125800, end_date=20250422T125801
[2025-04-22T12:58:01.604+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 11 for task Kafka_Producer (Bash command failed. The command returned a non-zero exit code 1.; 163)
[2025-04-22T12:58:01.619+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-22T12:58:01.643+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-22T12:58:01.644+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
