[2025-04-25T07:03:21.318+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-25T07:03:21.344+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_kafka_pipeline.spark_job scheduled__2025-04-25T06:40:00+00:00 [queued]>
[2025-04-25T07:03:21.349+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_kafka_pipeline.spark_job scheduled__2025-04-25T06:40:00+00:00 [queued]>
[2025-04-25T07:03:21.350+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 4
[2025-04-25T07:03:21.364+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): spark_job> on 2025-04-25 06:40:00+00:00
[2025-04-25T07:03:21.369+0000] {standard_task_runner.py:63} INFO - Started process 91 to run task
[2025-04-25T07:03:21.372+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'stock_kafka_pipeline', 'spark_job', 'scheduled__2025-04-25T06:40:00+00:00', '--job-id', '370', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpdjur5tnr']
[2025-04-25T07:03:21.374+0000] {standard_task_runner.py:91} INFO - Job 370: Subtask spark_job
[2025-04-25T07:03:21.411+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_kafka_pipeline.spark_job scheduled__2025-04-25T06:40:00+00:00 [running]> on host 9489df9b8294
[2025-04-25T07:03:21.479+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='stock_kafka_pipeline' AIRFLOW_CTX_TASK_ID='spark_job' AIRFLOW_CTX_EXECUTION_DATE='2025-04-25T06:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-25T06:40:00+00:00'
[2025-04-25T07:03:21.480+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-25T07:03:21.496+0000] {base.py:84} INFO - Using connection ID 'spark_default' for task execution.
[2025-04-25T07:03:21.497+0000] {spark_submit.py:328} ERROR - Failed to decode base64 keytab: Incorrect padding
[2025-04-25T07:03:21.497+0000] {spark_submit.py:305} INFO - Could not load connection string spark_default, defaulting to spark://172.21.0.8:7077:7077
[2025-04-25T07:03:21.498+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark3-submit --master spark://172.21.0.8:7077:7077 --conf spark.driver.memory=2g --conf spark.executor.memory=4g --principal *** --name arrow-spark --queue default --deploy-mode client Source/test.py
[2025-04-25T07:03:21.499+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-25T07:03:21.499+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 197, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 546, in submit
    self._submit_sp = subprocess.Popen(
                      ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'spark3-submit'
[2025-04-25T07:03:21.505+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_kafka_pipeline, task_id=spark_job, run_id=scheduled__2025-04-25T06:40:00+00:00, execution_date=20250425T064000, start_date=20250425T070321, end_date=20250425T070321
[2025-04-25T07:03:21.518+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 370 for task spark_job ([Errno 13] Permission denied: 'spark3-submit'; 91)
[2025-04-25T07:03:21.543+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-25T07:03:21.557+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-25T07:03:21.557+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
