[2025-04-25T07:05:53.954+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-25T07:05:54.001+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_kafka_pipeline.run_spark_test scheduled__2025-04-25T06:40:00+00:00 [queued]>
[2025-04-25T07:05:54.013+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_kafka_pipeline.run_spark_test scheduled__2025-04-25T06:40:00+00:00 [queued]>
[2025-04-25T07:05:54.013+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2025-04-25T07:05:54.034+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_spark_test> on 2025-04-25 06:40:00+00:00
[2025-04-25T07:05:54.042+0000] {standard_task_runner.py:63} INFO - Started process 161 to run task
[2025-04-25T07:05:54.044+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'stock_kafka_pipeline', 'run_spark_test', 'scheduled__2025-04-25T06:40:00+00:00', '--job-id', '373', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpqpua5syr']
[2025-04-25T07:05:54.046+0000] {standard_task_runner.py:91} INFO - Job 373: Subtask run_spark_test
[2025-04-25T07:05:54.094+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_kafka_pipeline.run_spark_test scheduled__2025-04-25T06:40:00+00:00 [running]> on host 9489df9b8294
[2025-04-25T07:05:54.167+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='stock_kafka_pipeline' AIRFLOW_CTX_TASK_ID='run_spark_test' AIRFLOW_CTX_EXECUTION_DATE='2025-04-25T06:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-25T06:40:00+00:00'
[2025-04-25T07:05:54.168+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-25T07:05:54.190+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-25T07:05:54.192+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit --master spark://172.21.0.8:7077  /opt/airflow/Scripts/test.py']
[2025-04-25T07:05:54.207+0000] {subprocess.py:86} INFO - Output:
[2025-04-25T07:05:54.221+0000] {subprocess.py:93} INFO - /home/airflow/.local/bin/find-spark-home: line 40: /usr/local/bin/python3.10: No such file or directory
[2025-04-25T07:05:54.222+0000] {subprocess.py:93} INFO - /home/airflow/.local/bin/spark-submit: line 27: /bin/spark-class: No such file or directory
[2025-04-25T07:05:54.223+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-04-25T07:05:54.224+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-25T07:05:54.232+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-04-25T07:05:54.236+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=stock_kafka_pipeline, task_id=run_spark_test, run_id=scheduled__2025-04-25T06:40:00+00:00, execution_date=20250425T064000, start_date=20250425T070554, end_date=20250425T070554
[2025-04-25T07:05:54.252+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 373 for task run_spark_test (Bash command failed. The command returned a non-zero exit code 127.; 161)
[2025-04-25T07:05:54.260+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-25T07:05:54.273+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-25T07:05:54.274+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
